#MODELS 1
regularization: True

interpolation: True

indicator: False



#MODELS 2
trials: 10 #number of trials for hyperparameter tuning

epochs: 10 #number of epochs for the traning part

balanced : False #True: balanced dataset / False: unbalanced dataset

repetition : 2