trials: 2 #number of trials for hyperparameter tuning

epochs: 1 #number of epochs for the traning part

balanced : True #True: balanced dataset / False: unbalanced dataset

repetition : 2 #number of times to retrain the model