#MODELS 1
#regularization: False
#
#interpolation: False
#
#indicator: False



#MODELS 2
trials: 50 #number of trials for hyperparameter tuning

epochs: 100 #number of epochs for the traning part

balanced : True #True: balanced dataset / False: unbalanced dataset

repetition : 6