#MODELS 1
#regularization: False
#
#interpolation: False
#
#indicator: False



#MODELS 2
trials: 2 #number of trials for hyperparameter tuning

epochs: 10 #number of epochs for the traning part

balanced : False #True: balanced dataset / False: unbalanced dataset

repetition : 2